version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ffp-app
    environment:
      MEDIA_DOWNLOAD_PATH: /app/downloads
    env_file:
      - .env
    volumes:
      # IMPORTANT: Persistent Telegram session storage (stored at root)
      - ./telegram_session.session:/app/telegram_session.session
      # SQLite database storage
      - ./ffp.db:/app/ffp.db
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    restart: unless-stopped

# Named volumes no longer needed since we're using bind mounts